### ISSUE TITLE
Anything you need patched in `AseAtomsAdaptor`?

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [ulissigroup/catapalt#2]
Hi @brookwander! I was just browsing GitHub and stumbled upon this WIP package. Since I wrote much of Pymatgen's `AseAtomsAdaptor`, I wanted to ask: was there anything you needed added/fixed in the upstream adapter? I noticed much of the code was copied/pasted below so wasn't sure if there was a workaround I should implement to help y'all out.

https://github.com/ulissigroup/catapalt/blob/ef82e934faeb424f063c8b860d91cb0ab19419fd/catapalt/atoms_adaptor.py#L18-L22

**Comment by brookwander** [comment]
Hello @arosen93, thanks for reaching out! This workaround makes it so that the tags attribute in Atoms gets cleanly passed through conversion to pymatgen structure and back. I can open a PR if you think it would be good to include. I was just trying to be mindful of not adding to the large amount of noise a large and important package like pymatgen sees, since I am not really sure who uses the tags attribute besides OCP people.

**Comment by Andrew-S-Rosen** [comment]
Hi @brookwander: Ah, good to know! My goal with the `AseAtomsAdaptor` is that everything gets retained, without exception. Feel free to open a PR and tag me to review if you'd like! Or not, entirely up to you :)

**Comment by brookwander** [comment]
Okay will do. Thanks for bringing this up!
